### ISSUE TITLE
Stuck in restoring state

### ISSUE THREAD

**Issue by SamuraiTheNinja** [JazzGlobal/DatabaseBackupTool#4]
While remoted into client site via simplehelp, we used the restore function to restore about 70 databases. I'd say probably half finished with no problem, the other half got stuck in "restoring" state. 

Don't know if its related but seems like the limiting factor (at least on my laptop with an NVME drive) was the drive itself when using the restore tool. When using the tool to restore 110 bak files on my laptop it did them all successfully but pegged the hard drive for as much as 1,200MB/s. The systems the clients have are at best using SATA SSDs with a max speed of 600MB\s 

Note: restoring 110 bak files to sql with the tool took ~30 seconds

**Comment by JazzGlobal** [comment]
This is probably because the app opens as many threads as there are .BAK files. So 110 restore procedures were occurring at the same time. 

If on a client box and if CEMDAS was running, this may explain the 50% success rate. I've reverted the build folder to the previous version where Threading was not included for DatabaseBackupTool. It is advised that you do not use the Restore Tool on client machines until this issue is closed.
